const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../engine.js');
const advance=(w,n)=>{for(let i=0;i<n;i++){E.tick(w);E.validate(w)}};
test('construction charges once, blocks work, persists and finishes on the exact round',()=>{let w=E.newWorld(1);w.money=1e6;E.command(w,{type:'demolish',tile:E.START_TILE});w.money=1e6;const t=w.tiles[E.START_TILE],cost=E.buildingCost(w,'camp');E.command(w,{type:'build',tile:t.id,buildType:'camp'});assert.equal(w.money,1e6-cost);const n=E.buildingProgress(w,t).duration;assert.throws(()=>E.command(w,{type:'worker',tile:t.id}),/施工/);assert.equal(E.productionState(w,t).active,false);advance(w,n-1);w=E.load(JSON.parse(JSON.stringify(w)));assert.equal(E.buildingProgress(w,w.tiles[t.id]).remaining,1);advance(w,1);assert.equal(E.buildingProgress(w,w.tiles[t.id]),null);E.command(w,{type:'worker',tile:t.id});assert.equal(E.productionState(w,w.tiles[t.id]).active,true);});
test('research delays effects and dependencies and prevents duplicate payment',()=>{let w=E.newWorld(1);w.money=1e6;E.command(w,{type:'tech',key:'quarry'});const money=w.money,n=E.techProgress(w,'quarry').duration;assert.equal(w.tech.quarry,0);assert.equal(w.money,money);advance(w,n-1);w=E.load(w);assert.equal(w.tech.quarry,0);advance(w,1);assert.equal(w.tech.quarry,1);assert.equal(E.techProgress(w,'quarry'),null);});
test('cost increases duration; legacy worlds stay complete; invalid progress is rejected',()=>{assert.ok(E.projectDuration(5000)>E.projectDuration(500));const w=E.load(E.newWorld(1));assert.deepEqual(E.projects(w),[]);w.research={quarry:{started:0,duration:-1}};assert.throws(()=>E.validate(w),/进度/);});

test('new projects are four times faster without rewriting an active saved project',()=>{assert.equal(E.projectDuration(600),10);assert.equal(E.projectDuration(1200),12);const w=E.newWorld(7);w.research={quarry:{started:0,duration:5}};assert.equal(E.techProgress(E.load(w),'quarry').duration,5);});

test('free clicks advance only the target, persist and finish immediately while paused',()=>{let w=E.newWorld(1);w.money=1e6;w.paused=true;E.command(w,{type:'demolish',tile:E.START_TILE});E.command(w,{type:'build',tile:E.START_TILE,buildType:'camp'});E.command(w,{type:'tech',key:'quarry'});const money=w.money,tick=w.tick;E.command(w,{type:'tech',key:'quarry'});assert.ok(E.techProgress(w,'quarry').done>0);assert.equal(E.buildingProgress(w,w.tiles[E.START_TILE]).done,0);w=E.load(JSON.parse(JSON.stringify(w)));assert.ok(E.techProgress(w,'quarry').done>0);for(let n=0;E.techProgress(w,'quarry')&&n<10;n++)w=E.apply(w,{type:'tech',key:'quarry'});assert.equal(w.tech.quarry,1);for(let n=0;E.buildingProgress(w,w.tiles[E.START_TILE])&&n<10;n++)w=E.apply(w,{type:'click',tile:E.START_TILE});assert.equal(E.buildingProgress(w,w.tiles[E.START_TILE]),null);assert.equal(w.money,money);assert.equal(w.tick,tick);assert.equal(w.manual.out.log,0);E.validate(w);});
