const {chromium}=require('C:/Users/fzhan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('node:url');const path=require('node:path');const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{fs.mkdirSync('tmp/mobile',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});try{
for(const [width,height] of [[390,844],[320,568],[740,900],[667,375],[1440,960]]){
 const context=await browser.newContext({viewport:{width,height},hasTouch:width<800});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve('index.html')).href);
 assert.equal(await page.locator('#mobile-advice').evaluate(e=>e.open),width<=740);
 if(width<=740){const tick=await page.evaluate(()=>world.tick);await page.waitForTimeout(1200);assert.equal(await page.evaluate(()=>world.tick),tick);await page.screenshot({path:`tmp/mobile/advice-${width}.png`});await page.getByRole('button',{name:'继续在手机上游玩'}).click();await page.reload();assert.equal(await page.locator('#mobile-advice').evaluate(e=>e.open),false);const scale=await page.evaluate(()=>view.scale);await page.locator('#map-plus').click();assert.ok(await page.evaluate(()=>view.scale)>scale);
 await page.evaluate(()=>{world.paused=true;const dispatch=(type,id,x,y)=>svg.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerType:'touch',pointerId:id,clientX:x,clientY:y,button:0}));window.touchDispatch=dispatch;dispatch('pointerdown',11,120,230);dispatch('pointerdown',12,220,230);});const before=await page.evaluate(()=>({scale:view.scale,money:world.money}));await page.evaluate(()=>{touchDispatch('pointermove',12,280,250);touchDispatch('pointerup',12,280,250);touchDispatch('pointerup',11,120,230);});assert.ok(await page.evaluate(()=>view.scale)>before.scale);assert.equal(await page.evaluate(()=>world.money),before.money);assert.equal(await page.evaluate(()=>gesture),null);
 }
 if(width<=740){const panel=await page.locator('.mobile-stack-wrap').boundingBox();assert.ok(panel.height<=height*.42+1,'bottom panel leaves map space');await page.locator('#map-home').click();const tile=await page.locator('[data-tile="0,0"]').first().count();await page.evaluate(()=>{buildType='camp';});const old=await page.evaluate(()=>view.x);await page.evaluate(()=>{touchDispatch('pointerdown',21,170,200);touchDispatch('pointermove',21,210,200);touchDispatch('pointerup',21,210,200);});assert.notEqual(await page.evaluate(()=>view.x),old,'can pan while building');assert.equal(await page.evaluate(()=>buildType),'camp');await page.evaluate(()=>{buildType=null;render();});}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`tmp/mobile/game-${width}.png`});await page.locator('#industry-open').click();const detail=await page.locator('.planner-details').boundingBox();assert.ok(detail.y+detail.height<=height+1,'planner details reachable');await page.screenshot({path:`tmp/mobile/planner-${width}.png`});await page.locator('#industry-close').click();
 await page.goto(pathToFileURL(path.resolve('docs/ui-components.html')).href);await page.locator('#mobile-demo button').first().click();assert.equal(await page.locator('#mobile-demo-dialog').evaluate(e=>e.open),true);await page.locator('#mobile-demo-dialog button').click();assert.deepEqual(errors,[]);await context.close();
}console.log('PASS mobile/desktop layouts, advice pause/session dismissal, zoom, pinch cancellation, planner reachability, isolated samples');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
