const test=require('node:test');const assert=require('node:assert/strict');require('../road-system.js');
function chain(n,{water=false,buildings=false}={}){const tiles=Object.fromEntries(Array.from({length:n+1},(_,i)=>[String(i),{id:String(i),terrain:water?'lake':'grass',x:i*85,building:buildings?{}:null}]));return RoadTiles.layout(tiles,Array.from({length:n},(_,i)=>({id:'e'+i,a:String(i),b:String(i+1)})),t=>[t.x,0]);}
const goods=l=>[...l.roads.values()].map(e=>({edge:e.id,from:e.a,to:e.b}));
const coverage=t=>t.planned.flatMap(r=>r.parts.map(p=>p.edge.id));
test('short land and water routes animate; buildings do not split a continuous long route',()=>{for(const water of [false,true]){const short=chain(1,{water}),t=RoadTiles.traffic(short,goods(short),0);assert.equal(t.routes.length,1);assert.match(RoadTiles.travelers(t,1),water?/freight-boat/:/freight-donkey/);}const l=chain(5,{buildings:true}),t=RoadTiles.traffic(l,goods(l),0);assert.equal(t.routes.length,1);assert.equal(t.routes[0].parts.length,5);assert.equal(RoadTiles.traffic(l,[],0).routes.length,0);});
test('longest line passes a junction first; uncovered short branch gets exactly one extra traveler',()=>{const l=chain(4,{buildings:true});l.roads.set('branch',{id:'branch',a:'2',b:'side',water:false,at:t=>[170,30*t]});const t=RoadTiles.traffic(l,goods(l),0);assert.equal(t.routes.length,2);assert.equal(t.planned[0].parts.length,4);assert.equal(coverage(t).length,5);assert.equal(new Set(coverage(t)).size,5);});
test('shipment destination uses actual engine path; orientation follows goods even on reversed edges',()=>{const l=chain(4);const t=RoadTiles.traffic(l,[{edge:'e0',from:'0',to:'1',destination:'4'}],0,null,()=>['e1','e2','e3']);assert.equal(t.routes[0].parts.length,4);const reversed=RoadTiles.traffic(l,goods(l).map(s=>({...s,from:s.to,to:s.from})),2,t);assert.ok(reversed.routes[0].at(.75)[0]<reversed.routes[0].at(.25)[0]);assert.equal(reversed.routes[0].started,2);});
test('land/water transitions use one traveler and switch model along the journey',()=>{const l=chain(4);l.roads.get('e2').water=true;l.roads.get('e3').water=true;const t=RoadTiles.traffic(l,goods(l),0),r=t.routes[0];assert.equal(t.routes.length,1);assert.match(RoadTiles.travelers(t,r.duration*.2),/freight-donkey/);assert.match(RoadTiles.travelers(t,r.duration*.8),/freight-boat/);l.roads.get('e2').removing=true;const removed=RoadTiles.traffic(l,goods(l),2,t);assert.ok(!coverage(removed).includes('e2'));});
test('six simultaneous travelers maximum with fair coverage of all queued routes, including brief flows',()=>{const l={roads:new Map(Array.from({length:12},(_,i)=>['r'+i,{id:'r'+i,a:'a'+i,b:'b'+i,water:i%2===0,at:t=>[t*40,i*20]}]))};let t=RoadTiles.traffic(l,goods(l),0),seen=new Set(t.routes.map(r=>r.id));assert.equal(t.routes.length,6);for(let time=1;time<=30;time++){t=RoadTiles.traffic(l,[],time,t);assert.ok(t.routes.length<=6);for(const r of t.routes)seen.add(r.id);}assert.equal(seen.size,12);assert.equal(t.routes.length,0);});
test('a long trip survives supply gaps, reduced motion is still, and an idle route does not restart',()=>{const l=chain(5);let t=RoadTiles.traffic(l,goods(l),0);const id=t.routes[0].id;assert.equal(RoadTiles.travelers(t,1,{reduced:true}),RoadTiles.travelers(t,20,{reduced:true}));t=RoadTiles.traffic(l,[],12,t);assert.equal(t.routes[0].id,id);assert.equal(t.routes[0].started,0);const r=t.routes[0];for(let p=.01;p<=1;p+=.01){const a=r.at(p-.01),b=r.at(p);assert.ok(Math.hypot(b[0]-a[0],b[1]-a[1])<5);}t=RoadTiles.traffic(l,[],100,t);assert.equal(t.routes.length,0);});
test('cycles are covered once and terminate',()=>{const l={roads:new Map([['a',{id:'a',a:'0',b:'1',at:t=>[80*t,0]}],['b',{id:'b',a:'1',b:'2',at:t=>[80,80*t]}],['c',{id:'c',a:'2',b:'0',at:t=>[80*(1-t),80*(1-t)]}]])};const t=RoadTiles.traffic(l,goods(l),0);assert.equal(t.routes.length,1);assert.equal(new Set(coverage(t)).size,3);});
